import os
import json
import time
import numpy as np
from agents.base_agent import BaseAgent
from utils.state_manager import SharedMemory

class ReportGenerationAgent(BaseAgent):
    def __init__(self):
        super().__init__("ReportGenerationAgent", "Clinical Scribe")

    def generate_narrative_report(self, state: SharedMemory) -> str:
        """Generates a professional narrative text report from the pipeline state."""
        patient_id = state.get("patient_id")
        timestamp = state.get("timestamp")
        video_path = state.get("video_path")
        
        mrvm = state.get("mrvm_features", {})
        hr = mrvm.get("heart_rate_bpm", state.get("heart_rate_bpm", 0.0))
        ef = state.get("ejection_fraction", 0.0)
        
        # Volumes
        volumes = state.get_nested("segmentations", "volumes", {})
        lv_vols = volumes.get("LV", [])
        min_vol = float(np.min(lv_vols)) if lv_vols else 0.0
        max_vol = float(np.max(lv_vols)) if lv_vols else 0.0
        
        preds = state.get("predictions", {})
        rhythm = preds.get("rhythm", "unknown").replace("_", " ").upper()
        confidence = preds.get("confidence", 0.0) * 100.0
        
        unc = state.get("uncertainty_metrics", {})
        requires_review = unc.get("requires_review", state.get("requires_review", False))
        
        sdnn = mrvm.get("sdnn_ms", 0.0)
        rmssd = mrvm.get("rmssd_ms", 0.0)
        lf_hf = mrvm.get("lf_hf_ratio", 1.0)
        
        motion = state.get("motion_tracking", {})
        dyssyn = motion.get("dyssynchrony_index_ms", state.get("dyssynchrony_index_ms", 0.0))
        motion_pattern = state.get("motion_pattern", "unknown")
        
        reasoning = state.get("reasoning", {})
        evidence_points = reasoning.get("evidence_points", [])
        evidence_str = "\n  * ".join(evidence_points) if evidence_points else "None"
        
        impression_text = reasoning.get("impression", "No reasoning summary compiled.")
        recs = reasoning.get("recommendations", [])
        recs_str = "\n  - ".join(recs) if recs else "None"
        
        review_flag = " [REQUIRES HUMAN CLINICAL REVIEW] " if requires_review else ""
        
        report_template = f"""===========================================================================
               ECHOCARDIOGRAM ARRHYTHMIA ASSESSMENT REPORT{review_flag}
===========================================================================
Patient ID: {patient_id}
Assessment Date: {timestamp}
Source Video: {os.path.basename(video_path)}
---------------------------------------------------------------------------

CARDIAC MEASUREMENTS:
  Heart Rate: {hr:.1f} BPM
  Ejection Fraction (LVEF): {ef:.1f}% ( Simpson's Method of Discs )
  Estimated LV Volume Range: {min_vol:.1f} - {max_vol:.1f} mL

RHYTHM ASSESSMENT:
  Detected Rhythm: {rhythm}
  Diagnostic Confidence: {confidence:.1f}%
  Decision Pathway: {state.get('decision_path', 'N/A')}

MECHANICAL RHYTHM VARIABILITY METRICS (MRVM):
  SDNN (Overall MRVM): {sdnn:.1f} ms
  RMSSD (Parasympathetic Index): {rmssd:.1f} ms
  LF/HF Ratio (Sympathovagal): {lf_hf:.2f}

MYOCARDIAL WALL MOTION ANALYSIS:
  Septal-Lateral Dyssynchrony Index: {dyssyn:.1f} ms
  Mechanical Motion Pattern: {motion_pattern.replace('_', ' ').capitalize()}
  Regional Mean Velocities:
    * Septal: {state.get('regional_scores', {}).get('septal', 0.0):.2f} pixels/frame
    * Lateral: {state.get('regional_scores', {}).get('lateral', 0.0):.2f} pixels/frame
    * Apical: {state.get('regional_scores', {}).get('apical', 0.0):.2f} pixels/frame
    * Basal: {state.get('regional_scores', {}).get('basal', 0.0):.2f} pixels/frame

DIAGNOSTIC EVIDENCE:
  * {evidence_str}

IMPRESSION:
  {impression_text}

RECOMMENDATIONS:
  - {recs_str}

---------------------------------------------------------------------------
NOTE: This assessment was generated by an automated multi-agent AI system 
analyzing echocardiogram mechanical motion curves WITHOUT an ECG.
Findings should be correlated with a standard 12-lead ECG or clinical context.
==========================================================================="""
        return report_template

    def execute(self, state: SharedMemory) -> SharedMemory:
        self.log("Assembling reports (narrative TXT and structured JSON)...")
        
        # 1. Generate text report
        narrative_report = self.generate_narrative_report(state)
        
        # 2. Generate EHR JSON structure
        mrvm = state.get("mrvm_features", {})
        motion = state.get("motion_tracking", {})
        preds = state.get("predictions", {})
        unc = state.get("uncertainty_metrics", {})
        reasoning = state.get("reasoning", {})
        
        structured_json = {
            "patient_id": state.get("patient_id"),
            "timestamp": state.get("timestamp"),
            "video_path": state.get("video_path"),
            "assessment": {
                "detected_rhythm": preds.get("rhythm", "unknown"),
                "confidence": float(preds.get("confidence", 0.0)),
                "requires_review": bool(unc.get("requires_review", False)),
                "decision_path": state.get("decision_path", "")
            },
            "metrics": {
                "heart_rate_bpm": float(mrvm.get("heart_rate_bpm", 0.0)),
                "ejection_fraction_pct": float(state.get("ejection_fraction", 0.0)),
                "irregularity_index": float(mrvm.get("irregularity_index", 0.0)),
                "sdnn_ms": float(mrvm.get("sdnn_ms", 0.0)),
                "rmssd_ms": float(mrvm.get("rmssd_ms", 0.0)),
                "pnn50_pct": float(mrvm.get("pnn50", 0.0)),
                "lf_ms2": float(mrvm.get("lf_power", 0.0)),
                "hf_ms2": float(mrvm.get("hf_power", 0.0)),
                "lf_hf_ratio": float(mrvm.get("lf_hf_ratio", 1.0)),
                "sd1": float(mrvm.get("sd1", 0.0)),
                "sd2": float(mrvm.get("sd2", 0.0)),
                "sd_ratio": float(mrvm.get("sd_ratio", 1.0)),
                "dyssynchrony_index_ms": float(motion.get("dyssynchrony_index_ms", 0.0)),
                "motion_irregularity": float(motion.get("motion_irregularity", 0.0))
            },
            "evidence": reasoning.get("evidence_points", []),
            "impression": reasoning.get("impression", ""),
            "recommendations": reasoning.get("recommendations", [])
        }
        
        # 3. Save to output directory `reports/`
        os.makedirs("reports", exist_ok=True)
        patient_id = state.get("patient_id")
        report_txt_path = f"reports/{patient_id}_report.txt"
        report_json_path = f"reports/{patient_id}_report.json"
        
        try:
            with open(report_txt_path, "w") as f:
                f.write(narrative_report)
            with open(report_json_path, "w") as f:
                json.dump(structured_json, f, indent=4)
            self.log(f"Saved clinical report text to {report_txt_path}")
            self.log(f"Saved clinical report JSON to {report_json_path}")
        except Exception as e:
            self.add_error(state, f"Failed to save clinical report files: {str(e)}")
            
        state.set("narrative_report", narrative_report)
        state.set("structured_json", structured_json)
        
        # Save report paths in state
        report_paths = {
            "txt": report_txt_path,
            "json": report_json_path,
            "pdf": ""
        }
        state.set("report_paths", report_paths)
        
        return state

# Alias for compatibility with project manager
ClinicalReportAgent = ReportGenerationAgent
