import os
import json
import time
from agents.base_agent import BaseAgent

class ClinicalReportAgent(BaseAgent):
    def __init__(self):
        super().__init__("ClinicalReportAgent", "Clinical Scribe")

    def generate_narrative_report(self, state: dict) -> str:
        """Generates a professional narrative text report from the pipeline state."""
        patient_id = state["patient_id"]
        timestamp = state["timestamp"]
        video_path = state["video_path"]
        
        hr = state.get("heart_rate_bpm", 0.0)
        ef = state.get("ejection_fraction", 0.0)
        
        # Volumes
        volume_curve = state.get("volume_curve")
        min_vol = float(np.min(volume_curve)) if volume_curve is not None else 0.0
        max_vol = float(np.max(volume_curve)) if volume_curve is not None else 0.0
        
        rhythm = state.get("rhythm", "unknown").replace("_", " ").upper()
        confidence = state.get("confidence", 0.0) * 100.0
        requires_review = state.get("requires_review", False)
        
        hrv_time = state.get("hrv_time", {})
        sdnn = hrv_time.get("sdnn_ms", 0.0)
        rmssd = hrv_time.get("rmssd_ms", 0.0)
        
        hrv_freq = state.get("hrv_freq", {})
        lf_hf = hrv_freq.get("lf_hf", 1.0)
        
        dyssyn = state.get("dyssynchrony_index_ms", 0.0)
        motion_pattern = state.get("motion_pattern", "unknown")
        
        evidence_points = state.get("evidence", [])
        evidence_str = "\n  * ".join(evidence_points) if evidence_points else "None"
        
        # Recommendations and Impression
        impression_text = self.get_impression(rhythm, hr, ef, confidence)
        recs = self.get_recommendations(rhythm, ef, confidence)
        recs_str = "\n  - ".join(recs)
        
        review_flag = " [REQUIRES HUMAN CLINICAL REVIEW] " if requires_review else ""
        
        report_template = f"""===========================================================================
               ECHOCARDIOGRAM ARRHYTHMIA ASSESSMENT REPORT{review_flag}
===========================================================================
Patient ID: {patient_id}
Assessment Date: {timestamp}
Source Video: {os.path.basename(video_path)}
---------------------------------------------------------------------------

CARDIAC MEASUREMENTS:
  Heart Rate: {hr:.1f} BPM
  Ejection Fraction (LVEF): {ef:.1f}% ( Simpson's Method of Discs )
  Estimated LV Volume Range: {min_vol:.1f} - {max_vol:.1f} mL

RHYTHM ASSESSMENT:
  Detected Rhythm: {rhythm}
  Diagnostic Confidence: {confidence:.1f}%
  Decision Pathway: {state.get('decision_path', 'N/A')}

MECHANICAL HEART RATE VARIABILITY (HRV):
  SDNN (Overall HRV): {sdnn:.1f} ms
  RMSSD (Parasympathetic Index): {rmssd:.1f} ms
  LF/HF Ratio (Sympathovagal): {lf_hf:.2f}

MYOCARDIAL WALL MOTION ANALYSIS:
  Septal-Lateral Dyssynchrony Index: {dyssyn:.1f} ms
  Mechanical Motion Pattern: {motion_pattern.replace('_', ' ').capitalize()}
  Regional Mean Velocities:
    * Septal: {state.get('regional_scores', {}).get('septal', 0.0):.2f} pixels/frame
    * Lateral: {state.get('regional_scores', {}).get('lateral', 0.0):.2f} pixels/frame
    * Apical: {state.get('regional_scores', {}).get('apical', 0.0):.2f} pixels/frame
    * Basal: {state.get('regional_scores', {}).get('basal', 0.0):.2f} pixels/frame

DIAGNOSTIC EVIDENCE:
  * {evidence_str}

IMPRESSION:
  {impression_text}

RECOMMENDATIONS:
  - {recs_str}

---------------------------------------------------------------------------
NOTE: This assessment was generated by an automated multi-agent AI system 
analyzing echocardiogram mechanical motion curves WITHOUT an ECG.
Findings should be correlated with a standard 12-lead ECG or clinical context.
==========================================================================="""
        return report_template

    def get_impression(self, rhythm: str, hr: float, ef: float, confidence: float) -> str:
        """Helper to write the clinical impression."""
        rhythm_lower = rhythm.lower()
        if "normal sinus rhythm" in rhythm_lower:
            return f"Normal left ventricular ejection fraction (EF: {ef:.1f}%) and regular heart rate (HR: {hr:.1f} BPM). Mechanical motion analysis indicates normal, synchronous cardiac cycles. No arrhythmia detected with {confidence:.1f}% confidence."
        elif "atrial fibrillation" in rhythm_lower:
            return f"Left ventricular volume curve displays high, chaotic rhythm irregularity (irregularity index: >0.15) and wall motion dyssynchrony. This pattern is highly suspicious for Atrial Fibrillation (AFib). Clinical validation with 12-lead ECG is strongly recommended. Ejection fraction is {ef:.1f}%."
        elif "pvc" in rhythm_lower:
            return f"Detecting localized myocardial wall motion dyssynchrony and isolated mechanical skips with compensatory pauses, indicative of Premature Ventricular Contractions (PVCs). Ejection fraction is {ef:.1f}%."
        elif "bradycardia" in rhythm_lower:
            return f"Mechanical heart rate is depressed at {hr:.1f} BPM, indicating Bradycardia. Cardiac cycles are regular. Assess for symptoms of bradycardia (dizziness, fatigue) and review medications. EF is {ef:.1f}%."
        elif "tachycardia" in rhythm_lower:
            return f"Mechanical heart rate is elevated at {hr:.1f} BPM, indicating Tachycardia. Cardiac cycles are regular. EF is {ef:.1f}%. Review for sinus tachycardia or underlying tachyrhythmias."
        else:
            return f"Undetermined cardiac rhythm detected ({rhythm}). Correlation with ECG recommended."

    def get_recommendations(self, rhythm: str, ef: float, confidence: float) -> list:
        """Helper to suggest clinical follow-up recommendations."""
        rhythm_lower = rhythm.lower()
        recs = []
        
        # General recommendations based on rhythm
        if "normal sinus rhythm" in rhythm_lower:
            recs.append("Routine clinical follow-up.")
            recs.append("No immediate cardiac rhythm monitoring indicated.")
        elif "atrial_fibrillation" in rhythm_lower or "atrial fibrillation" in rhythm_lower:
            recs.append("Urgent 12-lead ECG to confirm Atrial Fibrillation.")
            recs.append("Consider Holter monitoring / telemetry if transient.")
            recs.append("Evaluate stroke risk (CHA2DS2-VASc score) and consider anticoagulation.")
            recs.append("Refer to Cardiology / Electrophysiology.")
        elif "pvc" in rhythm_lower:
            recs.append("Obtain standard ECG / 24-hour Holter monitor to quantify PVC burden.")
            recs.append("Check electrolytes (potassium, magnesium) and thyroid panel.")
            recs.append("Avoid stimulants (caffeine, nicotine, alcohol).")
            recs.append("Refer to cardiology if PVC burden is high or symptomatic.")
        elif "bradycardia" in rhythm_lower:
            recs.append("Obtain 12-lead ECG to check for sinus bradycardia or heart block.")
            recs.append("Review medications for beta-blockers, calcium channel blockers, or digoxin.")
            recs.append("Correlate with clinical symptoms (syncope, dizziness).")
        elif "tachycardia" in rhythm_lower:
            recs.append("Obtain 12-lead ECG to identify tachycardia origin (sinus, SVT, etc.).")
            recs.append("Assess for underlying triggers: fever, pain, dehydration, anemia, hyperthyroidism.")
            
        # Low confidence recommendations
        if confidence < 85.0:
            recs.append("Flagged: Low diagnostic confidence. Perform manual validation of the volume curve and manual border tracking.")
            
        # Low EF recommendations
        if ef < 40.0:
            recs.append("Flagged: Reduced LVEF (<40%). Consider Guideline-Directed Medical Therapy (GDMT) for heart failure and schedule follow-up echo.")
        elif ef < 50.0:
            recs.append("Flagged: Borderline LVEF (40-50%). Repeat echocardiography in 6 months to monitor.")
            
        return recs

    def execute(self, state: dict) -> dict:
        # Import numpy for min/max
        global np
        import numpy as np
        
        # 1. Generate text report
        narrative_report = self.generate_narrative_report(state)
        
        # 2. Generate EHR JSON structure
        structured_json = {
            "patient_id": state["patient_id"],
            "timestamp": state["timestamp"],
            "video_path": state["video_path"],
            "assessment": {
                "detected_rhythm": state.get("rhythm", "unknown"),
                "confidence": float(state.get("confidence", 0.0)),
                "requires_review": bool(state.get("requires_review", False)),
                "decision_path": state.get("decision_path", "")
            },
            "metrics": {
                "heart_rate_bpm": float(state.get("heart_rate_bpm", 0.0)),
                "ejection_fraction_pct": float(state.get("ejection_fraction", 0.0)),
                "irregularity_index": float(state.get("irregularity_index", 0.0)),
                "sdnn_ms": float(state.get("hrv_time", {}).get("sdnn_ms", 0.0)),
                "rmssd_ms": float(state.get("hrv_time", {}).get("rmssd_ms", 0.0)),
                "pnn50_pct": float(state.get("hrv_time", {}).get("pnn50", 0.0)),
                "lf_ms2": float(state.get("hrv_freq", {}).get("lf_ms2", 0.0)),
                "hf_ms2": float(state.get("hrv_freq", {}).get("hf_ms2", 0.0)),
                "lf_hf_ratio": float(state.get("hrv_freq", {}).get("lf_hf", 1.0)),
                "sd1": float(state.get("hrv_nonlinear", {}).get("sd1", 0.0)),
                "sd2": float(state.get("hrv_nonlinear", {}).get("sd2", 0.0)),
                "sd_ratio": float(state.get("hrv_nonlinear", {}).get("sd_ratio", 1.0)),
                "dyssynchrony_index_ms": float(state.get("dyssynchrony_index_ms", 0.0)),
                "motion_irregularity": float(state.get("motion_irregularity", 0.0))
            },
            "evidence": state.get("evidence", []),
            "impression": self.get_impression(state.get("rhythm", "unknown"), state.get("heart_rate_bpm", 0.0), state.get("ejection_fraction", 0.0), state.get("confidence", 0.0)*100.0),
            "recommendations": self.get_recommendations(state.get("rhythm", "unknown"), state.get("ejection_fraction", 0.0), state.get("confidence", 0.0)*100.0)
        }
        
        # 3. Save to output directory `reports/`
        os.makedirs("reports", exist_ok=True)
        report_txt_path = f"reports/{state['patient_id']}_report.txt"
        report_json_path = f"reports/{state['patient_id']}_report.json"
        
        try:
            with open(report_txt_path, "w") as f:
                f.write(narrative_report)
            with open(report_json_path, "w") as f:
                json.dump(structured_json, f, indent=4)
            self.log(f"Saved clinical report text to {report_txt_path}")
            self.log(f"Saved clinical report JSON to {report_json_path}")
        except Exception as e:
            self.add_error(state, f"Failed to save clinical report files: {str(e)}")
            
        state["narrative_report"] = narrative_report
        state["structured_json"] = structured_json
        
        return state
